# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: py_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='py_rpc.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpy_rpc.proto\x12\x05proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x16\n\x07\x45\x63hoReq\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x16\n\x07\x45\x63hoRes\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1c\n\x0cLastPriceReq\x12\x0c\n\x04name\x18\x01 \x01(\t\"`\n\x0cLastPriceRsp\x12\r\n\x05\x65rror\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nclosePrice\x18\x04 \x01(\x01\x12\x11\n\topenPrice\x18\x05 \x01(\x01\x32=\n\x05Hello\x12\x34\n\x08SayHello\x12\x13.proto.HelloRequest\x1a\x11.proto.HelloReply\"\x00\x32.\n\x04\x45\x63ho\x12&\n\x04\x65\x63ho\x12\x0e.proto.EchoReq\x1a\x0e.proto.EchoRes2D\n\nStockPrice\x12\x36\n\x08GetPrice\x12\x13.proto.LastPriceReq\x1a\x13.proto.LastPriceRsp\"\x00\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='proto.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=51,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='proto.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)


_ECHOREQ = _descriptor.Descriptor(
  name='EchoReq',
  full_name='proto.EchoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.EchoReq.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=106,
)


_ECHORES = _descriptor.Descriptor(
  name='EchoRes',
  full_name='proto.EchoRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.EchoRes.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=130,
)


_LASTPRICEREQ = _descriptor.Descriptor(
  name='LastPriceReq',
  full_name='proto.LastPriceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.LastPriceReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=160,
)


_LASTPRICERSP = _descriptor.Descriptor(
  name='LastPriceRsp',
  full_name='proto.LastPriceRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.LastPriceRsp.error', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='proto.LastPriceRsp.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.LastPriceRsp.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closePrice', full_name='proto.LastPriceRsp.closePrice', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='openPrice', full_name='proto.LastPriceRsp.openPrice', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['EchoReq'] = _ECHOREQ
DESCRIPTOR.message_types_by_name['EchoRes'] = _ECHORES
DESCRIPTOR.message_types_by_name['LastPriceReq'] = _LASTPRICEREQ
DESCRIPTOR.message_types_by_name['LastPriceRsp'] = _LASTPRICERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

EchoReq = _reflection.GeneratedProtocolMessageType('EchoReq', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQ,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.EchoReq)
  })
_sym_db.RegisterMessage(EchoReq)

EchoRes = _reflection.GeneratedProtocolMessageType('EchoRes', (_message.Message,), {
  'DESCRIPTOR' : _ECHORES,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.EchoRes)
  })
_sym_db.RegisterMessage(EchoRes)

LastPriceReq = _reflection.GeneratedProtocolMessageType('LastPriceReq', (_message.Message,), {
  'DESCRIPTOR' : _LASTPRICEREQ,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.LastPriceReq)
  })
_sym_db.RegisterMessage(LastPriceReq)

LastPriceRsp = _reflection.GeneratedProtocolMessageType('LastPriceRsp', (_message.Message,), {
  'DESCRIPTOR' : _LASTPRICERSP,
  '__module__' : 'py_rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto.LastPriceRsp)
  })
_sym_db.RegisterMessage(LastPriceRsp)



_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='proto.Hello',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=260,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='proto.Hello.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO


_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='proto.Echo',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=323,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='proto.Echo.echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQ,
    output_type=_ECHORES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO


_STOCKPRICE = _descriptor.ServiceDescriptor(
  name='StockPrice',
  full_name='proto.StockPrice',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=371,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrice',
    full_name='proto.StockPrice.GetPrice',
    index=0,
    containing_service=None,
    input_type=_LASTPRICEREQ,
    output_type=_LASTPRICERSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCKPRICE)

DESCRIPTOR.services_by_name['StockPrice'] = _STOCKPRICE

# @@protoc_insertion_point(module_scope)
